import { useEffect, useRef, useState } from 'react';
import { toBlob } from 'html-to-image';
import packageInfo from '../package.json';
import type { AppData, Category, Friend, Language, PanelName } from './types';
import { t, type TranslationKey } from './i18n';
import { cryUrl, evolutionOptions, loadCatalog, spriteUrl, type CatalogEntry } from './catalog';
import { ACTIONS, encounterFromSeed, formatTime, hintFor, performAction, personalityName, petOutcome, type Action } from './game';
import { exportBackup, importBackup } from './store';
import { disableBackgroundNotifications, enableBackgroundNotifications, supportsBackgroundNotifications } from './pushNotifications';
import { usePokedoro } from './usePokedoro';
import { createId } from './id';
import { copyPlainText, encounterShareText } from './share';
import './styles.css';

type Setter=(update:(data:AppData)=>AppData)=>void;
const uid=()=>createId();
function MenuIcon({name}:{name:PanelName|'room'}){
 if(name==='room')return <svg viewBox="0 0 16 16" aria-hidden="true"><path d="M1 6V15H6V11C6 9.89543 6.89543 9 8 9C9.10457 9 10 9.89543 10 11V15H15V6L8 0L1 6Z"/></svg>;
 if(name==='focus')return <svg viewBox="0 0 24 24" aria-hidden="true"><path fillRule="evenodd" d="M8 3a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2H9a1 1 0 0 1-1-1zM3 14a9 9 0 0 1 14.618-7.032l.675-.675a1 1 0 1 1 1.414 1.414l-.675.675A9 9 0 1 1 3 14zm10-4a1 1 0 1 0-2 0v4a1 1 0 1 0 2 0v-4z" clipRule="evenodd"/></svg>;
 if(name==='todos')return <svg viewBox="0 0 512 512" aria-hidden="true"><path d="M469.402 35.492C334.09 110.664 197.114 324.5 197.114 324.5L73.509 184.176 0 254.336l178.732 222.172 65.15-2.504C327.414 223.414 512 55.539 512 55.539l-42.598-20.047z"/></svg>;
 if(name==='explore')return <svg viewBox="0 0 512 512" aria-hidden="true"><path d="M63.254 366.369c-2.515 0-4.894-.156-7.303-.272v25.096c0 13.392 10.877 24.269 24.28 24.269h14.237c13.403 0 24.28-10.878 24.28-24.269v-25.096c-2.409.116-4.788.272-7.312.272H63.254zM400.554 366.369c-2.515 0-4.894-.156-7.302-.272v25.096c0 13.392 10.877 24.269 24.279 24.269h14.237c13.403 0 24.279-10.878 24.279-24.269v-25.096c-2.408.116-4.787.272-7.312.272h-48.181zM132.334 183.215c2.71-12.81 5.565-26.144 8.799-39.469-10.625-24.697-26.456-42.236-53.784-42.236-60.232 0-64.69 85.172-80.307 144.549-20.074 76.286 4.031 104.402 56.212 104.402h48.181c3.195 0 6.196-.195 9.177-.409-12.878-28.426-12.693-67.584.894-119.26 3.894-14.81 7.264-30.727 10.828-47.577zM219.42 401.837c-.642 0-1.224-.059-1.865-.069v48.501c0 15.558 12.625 28.184 28.193 28.184h16.539c15.569 0 28.194-12.626 28.194-28.184V401.7c-1.233.02-2.39.136-3.642.136H219.42zM504.966 246.059c-15.626-59.378-20.084-144.549-80.316-144.549-30.563 0-46.763 21.919-57.348 51.268 2.37 10.295 4.545 20.521 6.643 30.437 3.564 16.85 6.934 32.767 10.828 47.578 13.499 51.345 13.762 90.319 1.137 118.697 4.632.583 9.44.972 14.645.972h48.181c52.199 0 76.284-28.116 56.23-104.403zM253.139 33.547c-84.298 0-90.533 119.182-112.395 202.305-28.076 106.752 5.643 146.095 78.676 146.095h67.419c73.071 0 106.771-39.343 78.694-146.095-21.861-83.123-28.095-202.305-112.394-202.305z"/></svg>;
 if(name==='friends')return <svg viewBox="0 0 16 16" aria-hidden="true"><path d="M1.24264 8.24264 8 15l6.7574-6.75736C15.553 7.44699 16 6.36786 16 5.24264v-.1903C16 2.8143 14.1857 1 11.9477 1c-1.2311 0-2.39537.55959-3.16439 1.52086L8 3.5l-.78331-.97914C6.44767 1.55959 5.28338 1 4.05234 1 1.8143 1 0 2.8143 0 5.05234v.1903c0 1.12522.44699 2.20435 1.24264 3z"/></svg>;
 if(name==='dex')return <svg viewBox="0 0 24 24" aria-hidden="true"><path fillRule="evenodd" d="M2.25 6A.75.75 0 0 1 3 5.25h17a.75.75 0 0 1 0 1.5H3A.75.75 0 0 1 2.25 6zm0 5a.75.75 0 0 1 .75-.75h6a.75.75 0 0 1 0 1.5H3a.75.75 0 0 1-.75-.75zm0 5a.75.75 0 0 1 .75-.75h7a.75.75 0 0 1 0 1.5H3a.75.75 0 0 1-.75-.75z" clipRule="evenodd"/><path d="M13 11.7148c0 1.7525 2.1633 3.6156 3.4901 4.5934.4541.3348.6812.5021 1.0099.5021s.5558-.1673 1.0099-.5021C19.8367 15.3304 22 13.4674 22 11.7147c0-2.67712-2.4751-3.67664-4.5-1.6086-2.0249-2.06804-4.5-1.06852-4.5 1.6087z"/></svg>;
 return <svg viewBox="0 0 8.466667 8.466667" aria-hidden="true"><g transform="translate(0 -288.53332)"><path transform="matrix(.26458333 0 0 .26458333 0 288.53332)" d="M14 1c-.43057-.000225-.812955.275154-.949219.683594L12.035156 4.73047c-.410051.144378-.81115.309902-1.203125.498047L7.958984 3.79297c-.385025-.192405-.849968-.116881-1.154296.1875L3.976562 6.808594c-.304381.304329-.379905.769272-.1875 1.154297l1.433594 2.867187c-.188579.39394-.355457.796828-.5 1.208984l-3.042969 1.015626c-.408439.136264-.683818.518648-.683593.949218v4c-.000225.43057.275154.812955.683593.949219l3.052735 1.017578c.143883.407584.309097.805606.496094 1.195313l-1.439454 2.878906c-.192405.385025-.116881.849968.1875 1.154297l2.828126 2.830078c.304328.304381.769271.379905 1.154296.1875l2.873047-1.4375c.391573.187086.791637.352283 1.201172.496094l1.017578 3.050781c.136264.40844.518649.683819.949219.683594h4c.43057.000225.812955-.275154.949219-.683594l1.017578-3.056641c.406496-.143244.804637-.308036 1.193359-.49414l2.88086 1.441406c.385025.192405.849967.116881 1.154296-.1875l2.828126-2.830078c.304381-.304329.379905-.769272.1875-1.154297l-1.435547-2.871094c.188179-.392579.353616-.794395.498047-1.205078l3.046874-1.015625c.40844-.136264.683819-.518649.683594-.949219v-4c.000225-.43057-.275155-.812954-.683594-.949218l-3.048828-1.015626c-.144351-.409397-.310214-.809839-.498046-1.201171l1.4375-2.875c.192405-.385025.116881-.849968-.1875-1.154297L25.195312 3.98047c-.304329-.304381-.769271-.379905-1.154296-.1875l-2.865235 1.43164c-.395249-.188976-.799375-.355281-1.21289-.5L18.949219 1.683594C18.812955 1.275154 18.43057.999775 18 1h-4zm1.996094 7.998047c3.854148 0 7.005859 3.151686 7.005859 7.005859 0 3.854136-3.151711 6.998047-7.005859 6.998047-3.854149 0-6.998047-3.143911-6.998047-6.998047 0-3.854173 3.143898-7.005859 6.998047-7.005859z"/></g></svg>;
}
const dateText=(iso:string,l:Language)=>new Intl.DateTimeFormat(l==='ko'?'ko-KR':l==='ja'?'ja-JP':'en-US',{dateStyle:'medium'}).format(new Date(iso));
const uiLabel=(l:Language,key:'selectMultiple'|'finishSelection'|'categoryAdd'|'petCooldown'|'seedInput'|'invalidSeed'|'explorationFailed'|'copyFailed'|'backgroundNotifications'|'notificationDenied'|'notificationUnavailable')=>({
  ko:{selectMultiple:'여러 개 선택',finishSelection:'선택 끝내기',categoryAdd:'카테고리 추가',petCooldown:'방금 쓰다듬었어요. 10분 뒤에 다시 교감할 수 있어요.',seedInput:'장소 시드 입력 (선택사항)',invalidSeed:'시드는 영문과 숫자 8자리로 입력해 주세요. 예: POKE-DORO',explorationFailed:'탐험을 시작하지 못했어요. 앱을 다시 열고 재시도해 주세요.',copyFailed:'공유 문구를 복사하지 못했어요. 클립보드 권한을 확인해 주세요.',backgroundNotifications:'백그라운드 알림',notificationDenied:'알림 권한을 허용해야 사용할 수 있어요.',notificationUnavailable:'이 브라우저에서는 백그라운드 알림을 지원하지 않아요.'},
  en:{selectMultiple:'Select multiple',finishSelection:'Finish selecting',categoryAdd:'Add category',petCooldown:'You just petted this Pokémon. Try again in 10 minutes.',seedInput:'Location seed (optional)',invalidSeed:'Enter exactly 8 letters or numbers. Example: POKE-DORO',explorationFailed:'Could not start the exploration. Reopen the app and try again.',copyFailed:'Could not copy the share text. Check clipboard permission.',backgroundNotifications:'Background notifications',notificationDenied:'Please allow notifications to use this feature.',notificationUnavailable:'Background notifications are not supported in this browser.'},
  ja:{selectMultiple:'複数選択',finishSelection:'選択を終了',categoryAdd:'カテゴリー追加',petCooldown:'なでたばかりです。10分後にもう一度ふれあえます。',seedInput:'場所シード（任意）',invalidSeed:'シードは英数字8文字で入力してください。例：POKE-DORO',explorationFailed:'探索を開始できませんでした。アプリを開き直して再試行してください。',copyFailed:'シェア文をコピーできませんでした。クリップボードの権限を確認してください。',backgroundNotifications:'バックグラウンド通知',notificationDenied:'この機能を使うには通知を許可してください。',notificationUnavailable:'このブラウザはバックグラウンド通知に対応していません。'}
}[l][key]);
const panelLabel=(l:Language,panel:PanelName|'room')=>panel==='focus'?(l==='ko'?'타이머':l==='ja'?'タイマー':'Timer'):t(l,panel);
const withKoreanSubject=(name:string)=>{const code=name.charCodeAt(name.length-1);return `${name}${code>=0xac00&&code<=0xd7a3&&(code-0xac00)%28!==0?'이':'가'}`};

function PokemonImage({id,shiny=false,style='pixel',className='',onClick}:{id:number;shiny?:boolean;style?:AppData['settings']['spriteStyle'];className?:string;onClick?:()=>void}){
 const [failed,setFailed]=useState(false); useEffect(()=>setFailed(false),[id,shiny,style]);
 return failed?<span className={`pokemon-fallback ${className}`}>?</span>:<img className={className} src={spriteUrl(id,shiny,style)} onError={()=>setFailed(true)} onClick={onClick} draggable={false}/>;
}

function MainWidget({data,setData,catalog,open,onToast}:{data:AppData;setData:Setter;catalog:CatalogEntry[];open:(x:PanelName)=>void;onToast:(x:string)=>void}){
 const ref=useRef<HTMLDivElement>(null), l=data.settings.language, room=data.friends.filter(x=>x.inRoom).slice(0,5);
 const remaining=data.timer.type==='pomodoro'?Math.max(0,data.timer.durationSeconds-data.timer.elapsedSeconds):data.timer.elapsedSeconds;
 const energy=Math.min(100,(data.focusBankSeconds/1800)*100);
 const bg=data.settings.customBackground||'./assets/meadow.jpg';
 async function capture(){if(!ref.current)return;try{const blob=await toBlob(ref.current,{cacheBust:true,pixelRatio:2});if(blob)await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);onToast(t(l,'captureCopied'));}catch{onToast('브라우저에서 이미지 클립보드 권한을 허용해주세요.');}}
 function sound(friend:Friend){if(data.settings.muted)return;const a=new Audio(cryUrl(friend.speciesId));a.volume=data.settings.cryVolume/100;a.play().catch(()=>{});}
 function toggleTimer(){setData(d=>({...d,timer:{...d.timer,running:!d.timer.running,lastTickAt:!d.timer.running?Date.now():null}}))}
 return <section className="widget" ref={ref} style={{backgroundImage:`linear-gradient(#ffffff0d,#ffffff0d),url(${bg})`}}>
   <div className={`energy-card ${data.settings.energyCollapsed?'collapsed':''}`}>
    <button className="round tiny" onClick={()=>setData(d=>({...d,settings:{...d.settings,energyCollapsed:!d.settings.energyCollapsed}}))}>{data.settings.energyCollapsed?'+':'−'}</button>
    {!data.settings.energyCollapsed&&<><strong>{t(l,'energy')}</strong><span>{Math.floor(energy)}%</span></>}<div className="bar"><i style={{width:`${energy}%`}}/></div>
   </div>
   <div className="top-actions"><button className="icon-button" aria-label="capture" onClick={capture}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="13" r="3"/><path d="M4 7.5h3l1.4-2h7.2l1.4 2h3v11H4z"/></svg></button><span className="ticket">{t(l,'ticket')} {data.tickets}/3</span></div>
   <div className="room">
    {room.map((friend,index)=><div key={friend.id} className={`room-pokemon p${index} ${data.settings.staticMode?'still':'walk'}`} onClick={()=>sound(friend)} onContextMenu={e=>{e.preventDefault();open('friends')}}>
      <PokemonImage id={friend.speciesId} shiny={friend.shiny} style={data.settings.spriteStyle}/>
    </div>)}
    {!data.settings.staticMode&&room.length>1&&<img className="speech" src="./assets/speech_bubbles/하트.png"/>}
   </div>
   <div className="widget-bottom"><div><b>{data.timer.mode==='focus'?t(l,'focus'):t(l,'break')}</b><strong>{formatTime(remaining)}</strong><span>{catalog.find(x=>x.id===Number(data.timer.selectedTodoId))?.names[l]??data.todos.find(x=>x.id===data.timer.selectedTodoId)?.title??''}</span></div><button onClick={toggleTimer} aria-label={data.timer.running?t(l,'pause'):t(l,'start')}>{data.timer.running?'Ⅱ':'▶'}</button></div>
 </section>;
}

function FocusTab({data,setData}:{data:AppData;setData:Setter}){
 const l=data.settings.language,timer=data.timer; const display=timer.type==='pomodoro'?Math.max(0,timer.durationSeconds-timer.elapsedSeconds):timer.elapsedSeconds;
 const [focus,setFocus]=useState(data.settings.focusMinutes),[rest,setRest]=useState(data.settings.breakMinutes);
 function updateSettings(){setData(d=>({...d,settings:{...d.settings,focusMinutes:Math.max(1,focus),breakMinutes:Math.max(1,rest)},timer:{...d.timer,durationSeconds:(d.timer.mode==='focus'?Math.max(1,focus):Math.max(1,rest))*60,elapsedSeconds:0}}));}
 function setType(type:AppData['timer']['type']){setData(d=>({...d,timer:{...d.timer,type,mode:'focus',elapsedSeconds:0,durationSeconds:d.settings.focusMinutes*60,running:false,lastTickAt:null}}));}
 function toggle(){if(typeof Notification!=='undefined'&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});setData(d=>({...d,timer:{...d.timer,running:!d.timer.running,lastTickAt:!d.timer.running?Date.now():null}}));}
 return <div className="tab-body focus-tab">
  <div className="segmented"><button className={timer.type==='pomodoro'?'active':''} onClick={()=>setType('pomodoro')}>{t(l,'pomodoro')}</button><button className={timer.type==='stopwatch'?'active':''} onClick={()=>setType('stopwatch')}>{t(l,'stopwatch')}</button></div>
  <div className="big-time">{formatTime(display)}</div>{timer.type==='pomodoro'&&<div className="mode-label">{timer.mode==='focus'?t(l,'focus'):t(l,'break')}</div>}
  <label>{t(l,'focusTask')}<select value={timer.selectedTodoId??''} onChange={e=>setData(d=>({...d,timer:{...d.timer,selectedTodoId:e.target.value||null}}))}><option value="">{t(l,'none')}</option>{data.todos.filter(x=>!x.completed).map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label>
  {timer.type==='pomodoro'&&<div className="time-settings"><label>{t(l,'focusTime')}<input type="number" min="1" max="999" value={focus} onChange={e=>setFocus(+e.target.value)}/>{t(l,'minute')}</label><label>{t(l,'breakTime')}<input type="number" min="1" max="999" value={rest} onChange={e=>setRest(+e.target.value)}/>{t(l,'minute')}</label><button onClick={updateSettings}>{t(l,'apply')}</button></div>}
  <div className="button-row"><button className="primary" onClick={toggle}>{timer.running?t(l,'pause'):timer.elapsedSeconds?t(l,'resume'):t(l,'start')}</button><button onClick={()=>setData(d=>({...d,timer:{...d.timer,running:false,elapsedSeconds:0,lastTickAt:null}}))}>{t(l,'stop')}</button>{timer.type==='pomodoro'&&<label className="toggle"><input type="checkbox" checked={timer.autoStart} onChange={e=>setData(d=>({...d,timer:{...d.timer,autoStart:e.target.checked}}))}/>{t(l,'auto')}</label>}</div>
 </div>;
}

function TodosTab({data,setData}:{data:AppData;setData:Setter}){
 const l=data.settings.language;const [title,setTitle]=useState(''),[hours,setHours]=useState(0),[minutes,setMinutes]=useState(0),[category,setCategory]=useState(''),[newCat,setNewCat]=useState(''),[selected,setSelected]=useState<Set<string>>(new Set()),[editing,setEditing]=useState<string|null>(null),[dragged,setDragged]=useState<string|null>(null),[categoryOpen,setCategoryOpen]=useState(false),[selectMode,setSelectMode]=useState(false);
 const sorted=[...data.todos].sort((a,b)=>a.sortOrder-b.sortOrder);
 function clear(){setTitle('');setHours(0);setMinutes(0);setCategory('');setEditing(null)}
 function submit(){if(!title.trim())return;const estimate=Math.max(0,hours)*60+Math.max(0,minutes);setData(d=>editing?({...d,todos:d.todos.map(x=>x.id===editing?{...x,title:title.trim(),categoryId:category||null,estimateMinutes:estimate}:x)}):({...d,todos:[...d.todos,{id:uid(),title:title.trim(),categoryId:category||null,estimateMinutes:estimate,focusSeconds:0,pomodoroCount:0,completed:false,sortOrder:d.todos.length}]}));clear()}
 function edit(id:string){const x=data.todos.find(v=>v.id===id);if(!x)return;setEditing(id);setTitle(x.title);setHours(Math.floor(x.estimateMinutes/60));setMinutes(x.estimateMinutes%60);setCategory(x.categoryId??'')}
 function reorder(over:string){if(!dragged||dragged===over)return;const ids=sorted.map(x=>x.id),from=ids.indexOf(dragged),to=ids.indexOf(over);ids.splice(to,0,ids.splice(from,1)[0]);setData(d=>({...d,todos:d.todos.map(x=>({...x,sortOrder:ids.indexOf(x.id)}))}));setDragged(null)}
 function toggleSelected(id:string){setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 function toggleDone(id:string){setData(d=>({...d,todos:d.todos.map(v=>v.id===id?{...v,completed:!v.completed,completedAt:!v.completed?new Date().toISOString():undefined}:v)}))}
 function addCategory(){if(!newCat.trim())return;const c:Category={id:uid(),name:newCat.trim()};setData(d=>({...d,categories:[...d.categories,c]}));setCategory(c.id);setNewCat('');setCategoryOpen(false)}
 return <div className="tab-body todos-tab"><div className="todo-tools"><span>{t(l,'newTask')}</span><button onClick={()=>setCategoryOpen(true)}>＋ {uiLabel(l,'categoryAdd')}</button></div><div className="todo-form"><input placeholder={t(l,'newTask')} value={title} onChange={e=>setTitle(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t(l,'noCategory')}</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label><input type="number" min="0" max="9999" value={hours} onChange={e=>setHours(+e.target.value)}/>{t(l,'hour')}</label><label><input type="number" min="0" max="59" value={minutes} onChange={e=>setMinutes(+e.target.value)}/>{t(l,'minute')}</label><button className="primary" onClick={submit}>{editing?t(l,'save'):t(l,'add')}</button>{editing&&<button onClick={clear}>{t(l,'cancel')}</button>}</div>
  <div className={`bulk ${selectMode?'selecting':''}`}><button onClick={()=>{setSelectMode(v=>!v);setSelected(new Set())}}>{selectMode?uiLabel(l,'finishSelection'):uiLabel(l,'selectMultiple')}</button>{!selectMode&&<small className="reorder-hint">{t(l,'dragHint')}</small>}{selectMode&&<><button disabled={!selected.size} onClick={()=>setData(d=>({...d,todos:d.todos.map(x=>selected.has(x.id)?{...x,completed:!x.completed,completedAt:!x.completed?new Date().toISOString():undefined}:x)}))}>{t(l,'bulkDone')}</button><button disabled={!selected.size} className="danger" onClick={()=>{if(selected.size&&confirm(`${selected.size}개를 삭제할까요?`)){setData(d=>({...d,todos:d.todos.filter(x=>!selected.has(x.id))}));setSelected(new Set())}}}>{t(l,'bulkDelete')}</button><b>{selected.size}</b></>}</div>
  <div className="todo-list">{sorted.map(x=><div className={`todo-row ${x.completed?'complete':''} ${selected.has(x.id)?'selected':''}`} key={x.id} draggable={!selectMode} onClick={()=>{if(selectMode)toggleSelected(x.id)}} onDragStart={()=>setDragged(x.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>reorder(x.id)}>{selectMode?<button className="select-dot" onClick={e=>{e.stopPropagation();toggleSelected(x.id)}} aria-label={uiLabel(l,'selectMultiple')}>{selected.has(x.id)?'●':'○'}</button>:<input className="completion-check" aria-label={t(l,'done')} type="checkbox" checked={x.completed} onClick={e=>e.stopPropagation()} onChange={()=>toggleDone(x.id)}/>}<span className="cat">{data.categories.find(c=>c.id===x.categoryId)?.name??'—'}</span><strong>{x.title}</strong><span className="todo-estimate">{t(l,'estimate')} {Math.floor(x.estimateMinutes/60)}{t(l,'hour')} {x.estimateMinutes%60}{t(l,'minute')}</span><span className="todo-actual">{t(l,'actual')} {Math.floor(x.focusSeconds/60)}{t(l,'minute')}</span><button className="todo-edit" aria-label={t(l,'edit')} onClick={e=>{e.stopPropagation();edit(x.id)}}>✎</button><button className="todo-delete danger" aria-label={t(l,'delete')} onClick={e=>{e.stopPropagation();if(confirm(`${x.title} — ${t(l,'delete')}?`))setData(d=>({...d,todos:d.todos.filter(todo=>todo.id!==x.id)}))}}>×</button></div>)}</div>
  {categoryOpen&&<div className="modal category-modal" onClick={()=>setCategoryOpen(false)}><article onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setCategoryOpen(false)}>×</button><small>{t(l,'category')}</small><h3>{uiLabel(l,'categoryAdd')}</h3><input autoFocus value={newCat} onChange={e=>setNewCat(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addCategory()}} placeholder={t(l,'newCategory')}/><div className="button-row"><button onClick={()=>setCategoryOpen(false)}>{t(l,'cancel')}</button><button className="primary" onClick={addCategory}>{t(l,'add')}</button></div></article></div>}
 </div>;
}

function ExploreTab({data,setData,catalog,onToast}:{data:AppData;setData:Setter;catalog:CatalogEntry[];onToast:(x:string)=>void}){
 const l=data.settings.language,[seed,setSeed]=useState(''),[exploring,setExploring]=useState(false),enc=data.encounter,info=enc?catalog.find(x=>x.id===enc.speciesId):null;
 async function begin(requestedSeed=seed){
  if(data.tickets<1||exploring)return;
  setExploring(true);
  try{
   const next=await encounterFromSeed(requestedSeed);
   setSeed('');
   setData(d=>({...d,tickets:d.tickets-1,encounter:next,dex:{...d.dex,[next.speciesId]:d.dex[next.speciesId]??{speciesId:next.speciesId,firstSeenAt:new Date().toISOString(),befriendedCount:0,shinySeen:next.shiny,shinyFriend:false}}}));
   if(!data.settings.muted){const a=new Audio(cryUrl(next.speciesId));a.volume=data.settings.cryVolume/100;a.play().catch(()=>{})}
  }catch(error){onToast(error instanceof Error&&error.message==='INVALID_PLACE_SEED'?uiLabel(l,'invalidSeed'):uiLabel(l,'explorationFailed'))}
  finally{setExploring(false)}
 }
 function action(a:Action){if(!enc)return;const next=performAction(enc,a);setData(d=>{let friends=d.friends;if(next.finished&&!enc.finished){const room=friends.filter(x=>x.inRoom);if(room.length){const chosen=room[Math.floor(Math.random()*room.length)];friends=friends.map(x=>x.id===chosen.id?{...x,intimacy:Math.min(99,x.intimacy+1),mood:'excited'}:x)}}if(!next.befriended||enc.befriended)return {...d,encounter:next,friends};const now=new Date().toISOString(),f:Friend={id:uid(),speciesId:enc.speciesId,personality:enc.personality,intimacy:1,mood:'happy',shiny:enc.shiny,metAt:now,befriendedAt:now,togetherSeconds:0,inRoom:friends.filter(x=>x.inRoom).length<5};const old=d.dex[enc.speciesId];return {...d,encounter:next,friends:[...friends,f],dex:{...d.dex,[enc.speciesId]:{...old,befriendedCount:(old?.befriendedCount??0)+1,shinySeen:(old?.shinySeen??false)||enc.shiny,shinyFriend:(old?.shinyFriend??false)||enc.shiny}}}});setTimeout(()=>setData(d=>d.encounter?.speciesId===next.speciesId?{...d,encounter:{...d.encounter,reaction:undefined}}:d),700)}
 async function share(){if(!enc)return;const name=info?.names[l]??`No.${enc.speciesId}`;const copied=await copyPlainText(encounterShareText(enc.seed,name,l));onToast(copied?t(l,'copied'):uiLabel(l,'copyFailed'))}
 if(!enc)return <div className="explore-landing"><div className="forest" style={{backgroundImage:"url('./assets/exploration-background.jpg')"}}><div className="forest-message"><strong>{t(l,'forestWaiting')}</strong><span>{t(l,'forestSub')}</span></div></div><div className="seed-row"><input value={seed} onChange={e=>setSeed(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void begin(seed.trim()?seed:'')}} placeholder={uiLabel(l,'seedInput')}/><button onClick={()=>void begin(seed)} disabled={!data.tickets||exploring||!seed.trim()}>{t(l,'seedExplore')}</button><button className="random-explore" onClick={()=>void begin('')} disabled={!data.tickets||exploring}>{l==='ko'?'무작위 탐험':t(l,'randomExplore')}</button></div></div>;
 const encounterName=info?.names[l]??`No.${enc.speciesId}`;
 return <div className="tab-body encounter"><div className="encounter-stage" style={{backgroundImage:"url('./assets/exploration-background.jpg')"}}><PokemonImage className={`wild ${enc.reaction??''}`} id={enc.speciesId} shiny={enc.shiny} style={data.settings.spriteStyle}/>{enc.shiny&&<b className="sparkle">✨ {t(l,'shiny')}!</b>}<div className="forest-message"><strong>{encounterName}</strong><span>{t(l,'encounterIntro')} {hintFor(enc.personality,l)}</span></div></div><label>{t(l,'distance')}<progress max="100" value={enc.distance}/>{enc.distance}%</label>{!enc.finished?<div className="action-grid">{ACTIONS.map(a=><button key={a} onClick={()=>action(a)}>{t(l,a as TranslationKey)}</button>)}</div>:<div className="result"><strong>{enc.befriended?`${l==='ko'?withKoreanSubject(encounterName):encounterName} ${t(l,'befriendedMsg')}`:t(l,'fled')}</strong><button onClick={share}>{t(l,'copyShare')}</button><button onClick={()=>setData(d=>({...d,encounter:null}))}>{t(l,'again')}</button></div>}</div>;
}

function FriendsTab({data,setData,catalog,onToast}:{data:AppData;setData:Setter;catalog:CatalogEntry[];onToast:(x:string)=>void}){
 const l=data.settings.language,[query,setQuery]=useState(''),[chosen,setChosen]=useState<Friend|null>(null),petLocks=useRef(new Set<string>());const filtered=data.friends.filter(f=>(catalog.find(x=>x.id===f.speciesId)?.names[l]??'').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.inRoom)-Number(a.inRoom));
 async function pet(friend:Friend){if(petLocks.current.has(friend.id))return;const now=new Date(),outcome=petOutcome(friend,now);if(!outcome.allowed){onToast(uiLabel(l,'petCooldown'));return}petLocks.current.add(friend.id);try{let intimacy=outcome.intimacy,speciesId=friend.speciesId,evolved=false;if(intimacy>=100){const options=await evolutionOptions(speciesId);if(options.length){speciesId=options[Math.floor(Math.random()*options.length)];intimacy=1;evolved=true;onToast(t(l,'evolved'));}}setData(d=>{const dex=d.dex[speciesId]??{speciesId,firstSeenAt:now.toISOString(),befriendedCount:1,shinySeen:friend.shiny,shinyFriend:friend.shiny};return {...d,friends:d.friends.map(x=>x.id===friend.id?{...x,intimacy,speciesId,lastPetAt:now.toISOString()}:x),dex:{...d.dex,[speciesId]:dex}}});if(!evolved)onToast(`${t(l,'pet')} +${outcome.gain}`)}finally{setTimeout(()=>petLocks.current.delete(friend.id),300)}}
 function toggleRoom(friend:Friend){if(!friend.inRoom&&data.friends.filter(x=>x.inRoom).length>=5){onToast(t(l,'roomFull'));return}setData(d=>({...d,friends:d.friends.map(x=>x.id===friend.id?{...x,inRoom:!x.inRoom}:x)}))}
 return <div className="tab-body"><input className="search" placeholder={t(l,'search')} value={query} onChange={e=>setQuery(e.target.value)}/><div className="friend-grid">{filtered.map(f=>{const name=catalog.find(x=>x.id===f.speciesId)?.names[l]??`No.${f.speciesId}`;return <article className="friend-card" key={f.id}><PokemonImage id={f.speciesId} shiny={f.shiny} style={data.settings.spriteStyle}/><div><strong>{f.shiny&&'✨ '}{name}</strong><span>{personalityName(f.personality,l)} · ♥ {f.intimacy}</span></div><button onClick={()=>toggleRoom(f)}>{f.inRoom?t(l,'remove'):t(l,'place')}</button><button onClick={()=>pet(f)}>{t(l,'pet')}</button><button onClick={()=>{if(!data.settings.muted){const a=new Audio(cryUrl(f.speciesId));a.volume=data.settings.cryVolume/100;a.play().catch(()=>{})}}}>{t(l,'cry')}</button><button onClick={()=>setChosen(f)}>{t(l,'status')}</button></article>})}</div>{chosen&&<div className="modal" onClick={()=>setChosen(null)}><article onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setChosen(null)}>×</button><PokemonImage id={chosen.speciesId} shiny={chosen.shiny} style={data.settings.spriteStyle}/><h3>{catalog.find(x=>x.id===chosen.speciesId)?.names[l]}</h3><p>{t(l,'personality')}: {personalityName(chosen.personality,l)}</p><p>{t(l,'intimacy')}: {chosen.intimacy}/100</p><p>{t(l,'met')}: {dateText(chosen.befriendedAt,l)}</p><p>{t(l,'together')}: {formatTime(chosen.togetherSeconds)}</p><button className="danger" onClick={()=>{if(confirm(t(l,'confirmRelease'))){setData(d=>({...d,friends:d.friends.filter(x=>x.id!==chosen.id)}));setChosen(null)}}}>{t(l,'release')}</button></article></div>}</div>;
}

function DexTab({data,catalog}:{data:AppData;catalog:CatalogEntry[]}){const l=data.settings.language,[query,setQuery]=useState('');const list=catalog.filter(x=>x.names[l].toLowerCase().includes(query.toLowerCase())||String(x.id).includes(query));return <div className="tab-body dex-tab"><div className="dex-head"><input placeholder={t(l,'search')} value={query} onChange={e=>setQuery(e.target.value)}/><span>{t(l,'discovered')} {Object.keys(data.dex).length}/{catalog.length} · {t(l,'befriended')} {new Set(data.friends.map(x=>x.speciesId)).size}</span></div><div className="dex-list">{list.map(x=>{const seen=!!data.dex[x.id];return <div key={x.id} className={!seen?'unknown':''}><span>No.{String(x.id).padStart(4,'0')}</span><PokemonImage id={x.id} style="pixel"/><strong>{seen?x.names[l]:'???'}</strong>{data.dex[x.id]?.shinySeen&&<i>✨</i>}</div>})}</div></div>}

function SettingsTab({data,setData,onToast}:{data:AppData;setData:Setter;onToast:(x:string)=>void}){
  const l=data.settings.language;
  function fileBg(file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>setData(d=>({...d,settings:{...d.settings,customBackground:String(reader.result)}}));reader.readAsDataURL(file)}
  async function toggleBackgroundNotifications(enabled:boolean){
    if(enabled){
      if(!supportsBackgroundNotifications()){onToast(uiLabel(l,'notificationUnavailable'));return}
      try{if(!await enableBackgroundNotifications()){onToast(uiLabel(l,'notificationDenied'));return}}
      catch{onToast(uiLabel(l,'notificationUnavailable'));return}
    }else await disableBackgroundNotifications().catch(()=>undefined);
    setData(d=>({...d,settings:{...d.settings,backgroundNotifications:enabled}}));
  }
  return <div className="tab-body settings-grid"><label>{t(l,'language')}<select value={l} onChange={e=>setData(d=>({...d,settings:{...d.settings,language:e.target.value as Language}}))}><option value="ko">한국어</option><option value="en">English</option><option value="ja">日本語</option></select></label><label>{t(l,'volume')}<input type="range" min="0" max="100" value={data.settings.cryVolume} onChange={e=>setData(d=>({...d,settings:{...d.settings,cryVolume:+e.target.value}}))}/>{data.settings.cryVolume}%</label><label className="toggle"><input type="checkbox" checked={data.settings.muted} onChange={e=>setData(d=>({...d,settings:{...d.settings,muted:e.target.checked}}))}/>{t(l,'mute')}</label><label className="toggle"><input type="checkbox" checked={data.settings.backgroundNotifications} onChange={e=>void toggleBackgroundNotifications(e.target.checked)}/>{uiLabel(l,'backgroundNotifications')}</label><label className="toggle"><input type="checkbox" checked={data.settings.staticMode} onChange={e=>setData(d=>({...d,settings:{...d.settings,staticMode:e.target.checked}}))}/>{t(l,'staticMode')}</label><label>{t(l,'sprite')}<select value={data.settings.spriteStyle} onChange={e=>setData(d=>({...d,settings:{...d.settings,spriteStyle:e.target.value as AppData['settings']['spriteStyle']}}))}><option value="pixel">{t(l,'pixel')}</option><option value="home">{t(l,'home')}</option><option value="official">{t(l,'official')}</option></select></label><label>{t(l,'theme')}<select value={data.settings.colorTheme} onChange={e=>setData(d=>({...d,settings:{...d.settings,colorTheme:e.target.value as AppData['settings']['colorTheme']}}))}><option value="meadow">Meadow</option><option value="blossom">Blossom</option><option value="lavender">Lavender</option><option value="ocean">Ocean</option><option value="sunset">Sunset</option></select></label><fieldset><legend>{t(l,'background')}</legend><small>{t(l,'recommendation')}</small><input type="file" accept="image/*" onChange={e=>fileBg(e.target.files?.[0])}/><button onClick={()=>setData(d=>({...d,settings:{...d.settings,customBackground:''}}))}>{t(l,'defaultBg')}</button></fieldset><fieldset><legend>{t(l,'backup')}</legend><button onClick={()=>exportBackup(data)}>{t(l,'export')}</button><label className="file-button">{t(l,'import')}<input hidden type="file" accept="application/json" onChange={async e=>{try{const f=e.target.files?.[0];if(f){const imported=await importBackup(f);setData(()=>imported)}}catch{onToast(t(l,'backupInvalid'))}}}/></label></fieldset></div>
}

export default function App(){const {data,setData,toast,setToast}=usePokedoro();const [catalog,setCatalog]=useState<CatalogEntry[]>([]),[tab,setTab]=useState<PanelName|'room'>('room'),[menuOpen,setMenuOpen]=useState(false);useEffect(()=>{loadCatalog().then(setCatalog)},[]);if(!data)return <div className="loading">POKEDORO…</div>;const update:Setter=fn=>setData(previous=>previous?fn(previous):previous);const l=data.settings.language;const open=(x:PanelName|'room')=>{setTab(x);setMenuOpen(false)};const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(''),2400)};const panels=(['focus','todos','explore','friends','dex','settings'] as PanelName[]);return <main className={`app theme-${data.settings.colorTheme}`}>
 <header className="app-header"><button className={`menu-trigger ${menuOpen?'open':''}`} onClick={()=>setMenuOpen(v=>!v)} aria-label={t(l,'menu')} aria-expanded={menuOpen}><i/><i/><i/></button><div className="brand"><strong>POKEDORO ·WEB</strong><span>{panelLabel(l,tab)}</span></div></header>
 {menuOpen&&<button className="menu-scrim" aria-label={t(l,'close')} onClick={()=>setMenuOpen(false)}/>}
 <aside className={`side-menu ${menuOpen?'open':''}`} aria-hidden={!menuOpen}><div className="menu-heading"><strong>POKEDORO</strong><span>{t(l,'menu')}</span></div><nav><button onClick={()=>open('room')} className={tab==='room'?'active':''}><span><MenuIcon name="room"/></span>{t(l,'room')}</button>{panels.map(x=><button key={x} onClick={()=>open(x)} className={tab===x?'active':''}><span><MenuIcon name={x}/></span>{panelLabel(l,x)}</button>)}</nav><small>Timer · Explore · Befriend</small></aside>
 <section className="screen">{tab==='room'?<MainWidget data={data} setData={update} catalog={catalog} open={x=>open(x)} onToast={notify}/>:<section className="workspace"><header><span className="panel-symbol"><MenuIcon name={tab}/></span><div><small>POKEDORO</small><h1>{panelLabel(l,tab)}</h1></div></header>{tab==='focus'&&<FocusTab data={data} setData={update}/>} {tab==='todos'&&<TodosTab data={data} setData={update}/>} {tab==='explore'&&<ExploreTab data={data} setData={update} catalog={catalog} onToast={notify}/>} {tab==='friends'&&<FriendsTab data={data} setData={update} catalog={catalog} onToast={notify}/>} {tab==='dex'&&<DexTab data={data} catalog={catalog}/>} {tab==='settings'&&<SettingsTab data={data} setData={update} onToast={notify}/>}</section>}</section>
 {tab==='friends'&&<button className="friends-scroll-top" type="button" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label={l==='ko'?'맨 위로':l==='ja'?'一番上へ':'Back to top'}><svg fill="#000000" viewBox="-4.8 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><g strokeWidth="0"/><g strokeLinecap="round" strokeLinejoin="round"/><g><title>up</title><path d="M11.25 15.688l-7.656 7.656-3.594-3.688 11.063-11.094 11.344 11.344-3.5 3.5z"/></g></svg></button>}
 <footer className="app-version">POKEDORO v{packageInfo.version}</footer>
 {toast&&<div className="toast">{toast==='ticket'?t(l,'ticketEarned'):toast}</div>}</main>}
