import type { Language } from './types';

const ko = {
 room:'포켓몬 룸',focus:'집중',todos:'할 일',explore:'탐험',friends:'친구 목록',dex:'전국도감',settings:'설정',start:'시작',pause:'일시정지',resume:'계속',stop:'중단하고 기록',auto:'자동',pomodoro:'뽀모도로',stopwatch:'타이머 · 카운트업',focusTime:'집중 시간',breakTime:'휴식 시간',focusTask:'집중할 일',none:'선택하지 않음',break:'휴식',hour:'시간',minute:'분',apply:'시간 적용',add:'추가',edit:'수정',save:'저장',cancel:'취소',delete:'삭제',done:'완료',category:'카테고리',noCategory:'카테고리 없음',newCategory:'새 카테고리',newTask:'새로운 할 일',estimate:'예상',actual:'실제 집중',bulkDone:'선택 완료 전환',bulkDelete:'선택 삭제',dragHint:'끌어서 우선순위를 바꿀 수 있어요.',locationSeed:'장소 시드',seedExplore:'이 장소에서 탐험',depart:'탐험권 1장으로 출발',copyShare:'공유 문구 복사',hint:'힌트',distance:'마음의 거리',approach:'천천히 다가간다',wait:'기다려본다',play:'놀아준다',snack:'간식을 건넨다',petTry:'쓰다듬으려 한다',again:'다시 탐험하기',search:'검색',place:'방에 배치',remove:'방에서 제외',pet:'쓰다듬기',status:'상태 보기',cry:'울음소리 듣기',release:'놓아주기',personality:'성격',intimacy:'친밀도',mood:'현재 기분',met:'친구가 된 날',together:'함께한 시간',language:'언어',sound:'소리',volume:'볼륨',mute:'음소거',staticMode:'정적 모드',theme:'컬러 테마',sprite:'포켓몬 이미지',pixel:'도트 스프라이트',home:'HOME 일러스트',official:'공식 일러스트',background:'메인 화면 배경',chooseImage:'배경 이미지 선택',defaultBg:'기본 배경',backup:'데이터 백업',export:'백업 내보내기',import:'백업 가져오기',ticketEarned:'탐험권을 얻었어요!',copied:'클립보드에 복사했어요.',captureCopied:'메인 화면을 이미지로 복사했어요.',noPokemon:'포켓몬을 찾지 못했어요.',energy:'탐사 에너지',ready:'탐험 준비 완료!',ticket:'탐험권',menu:'메뉴',close:'닫기',shiny:'이로치',discovered:'발견',befriended:'친구',roomFull:'우리 방에는 최대 5마리까지 배치할 수 있어요.',confirmRelease:'정말 놓아줄까요? 이 작업은 되돌릴 수 없어요.',evolved:'친밀도 100! 포켓몬이 진화했어요!',encounterIntro:'처음 보는 포켓몬이 이쪽을 살피고 있다.',befriendedMsg:'네 곁에 남고 싶어 한다!',fled:'포켓몬이 풀숲으로 돌아갔다.',seedPlaceholder:'공유받은 시드 또는 원하는 문구',debug:'테스트: 집중 30분 채우기',reset:'초기화',statusTitle:'포켓몬 상태',recommendation:'권장 크기 640×280px 이상의 가로 이미지',install:'앱 설치',forestWaiting:'풀숲이 조용히 기다리고 있어요.',forestSub:'집중해서 얻은 탐험권으로 출발해 보세요.',timerDone:'타이머가 완료되었습니다.',backupInvalid:'올바른 POKEDORO 백업 파일이 아닙니다.'
};
type Key = keyof typeof ko;
const en: Partial<Record<Key,string>> = {
 room:'Pokémon Room',focus:'Focus',todos:'Tasks',explore:'Explore',friends:'Friends',dex:'National Dex',settings:'Settings',start:'Start',pause:'Pause',resume:'Resume',stop:'Stop & save',auto:'Auto',pomodoro:'Pomodoro',stopwatch:'Stopwatch · Count up',focusTime:'Focus time',breakTime:'Break time',focusTask:'Focus task',none:'None',break:'Break',hour:'h',minute:'m',apply:'Apply',add:'Add',edit:'Edit',save:'Save',cancel:'Cancel',delete:'Delete',done:'Done',category:'Category',noCategory:'No category',newCategory:'New category',newTask:'New task',estimate:'Estimate',actual:'Focused',bulkDone:'Toggle selected',bulkDelete:'Delete selected',dragHint:'Drag tasks to reorder.',locationSeed:'Location seed',seedExplore:'Explore this location',depart:'Depart with 1 ticket',copyShare:'Copy share text',hint:'Hint',distance:'Friendship',approach:'Approach slowly',wait:'Wait',play:'Play',snack:'Offer a snack',petTry:'Try to pet',again:'Explore again',search:'Search',place:'Place in room',remove:'Remove from room',pet:'Pet',status:'View status',cry:'Play cry',release:'Release',personality:'Personality',intimacy:'Friendship',mood:'Mood',met:'Befriended',together:'Time together',language:'Language',sound:'Sound',volume:'Volume',mute:'Mute',staticMode:'Static mode',theme:'Color theme',sprite:'Pokémon image',pixel:'Pixel sprite',home:'HOME artwork',official:'Official artwork',background:'Main background',chooseImage:'Choose image',defaultBg:'Default',backup:'Data backup',export:'Export backup',import:'Import backup',ticketEarned:'You earned an exploration ticket!',copied:'Copied to clipboard.',captureCopied:'Widget image copied.',noPokemon:'No Pokémon found.',energy:'Exploration energy',ready:'Ready to explore!',ticket:'Tickets',menu:'Menu',close:'Close',shiny:'Shiny',discovered:'Seen',befriended:'Friends',roomFull:'Up to 5 Pokémon can stay in the room.',confirmRelease:'Release this Pokémon? This cannot be undone.',evolved:'Friendship 100! Your Pokémon evolved!',encounterIntro:'A wild Pokémon is watching you carefully.',befriendedMsg:'It wants to stay by your side!',fled:'The Pokémon returned to the grass.',seedPlaceholder:'Enter a shared seed or any phrase',debug:'Test: add 30 focus minutes',reset:'Reset',statusTitle:'Pokémon status',recommendation:'Recommended: a landscape image at least 640×280px',install:'Install app',forestWaiting:'The grass is quietly waiting.',forestSub:'Set out with a ticket earned by focusing.',timerDone:'The timer is complete.',backupInvalid:'This is not a valid POKEDORO backup.'
};
const ja: Partial<Record<Key,string>> = {
 room:'ポケモンルーム',focus:'集中',todos:'やること',explore:'探索',friends:'なかま',dex:'全国図鑑',settings:'設定',start:'スタート',pause:'一時停止',resume:'再開',stop:'終了して記録',auto:'自動',pomodoro:'ポモドーロ',stopwatch:'タイマー・カウントアップ',focusTime:'集中時間',breakTime:'休憩時間',focusTask:'集中するタスク',none:'選択なし',break:'休憩',hour:'時間',minute:'分',apply:'時間を適用',add:'追加',edit:'編集',save:'保存',cancel:'キャンセル',delete:'削除',done:'完了',category:'カテゴリー',noCategory:'カテゴリーなし',newCategory:'新しいカテゴリー',newTask:'新しいタスク',estimate:'予想',actual:'実集中',bulkDone:'選択を完了切替',bulkDelete:'選択を削除',dragHint:'ドラッグで優先順位を変更できます。',locationSeed:'場所シード',seedExplore:'この場所を探索',depart:'探索券1枚で出発',copyShare:'シェア文をコピー',hint:'ヒント',distance:'心の距離',approach:'ゆっくり近づく',wait:'待ってみる',play:'遊んであげる',snack:'おやつを渡す',petTry:'なでてみる',again:'もう一度探索',search:'検索',place:'部屋に出す',remove:'部屋から外す',pet:'なでる',status:'状態を見る',cry:'鳴き声を聞く',release:'お別れする',personality:'性格',intimacy:'なかよし度',mood:'今の気分',met:'出会った日',together:'一緒の時間',language:'言語',sound:'サウンド',volume:'音量',mute:'ミュート',staticMode:'静止モード',theme:'カラーテーマ',sprite:'ポケモン画像',pixel:'ドット絵',home:'HOMEイラスト',official:'公式イラスト',background:'メイン背景',chooseImage:'背景画像を選択',defaultBg:'標準に戻す',backup:'データバックアップ',export:'書き出す',import:'読み込む',ticketEarned:'探索券を獲得しました！',copied:'クリップボードにコピーしました。',captureCopied:'メイン画面を画像でコピーしました。',noPokemon:'ポケモンが見つかりません。',energy:'探索エネルギー',ready:'探索の準備完了！',ticket:'探索券',menu:'メニュー',close:'閉じる',shiny:'色違い',discovered:'発見',befriended:'なかま',roomFull:'部屋に出せるのは5匹までです。',confirmRelease:'本当にお別れしますか？元に戻せません。',evolved:'なかよし度100！ポケモンが進化しました！',encounterIntro:'見知らぬポケモンがこちらの様子を見ている。',befriendedMsg:'あなたのそばに残りたいようだ！',fled:'ポケモンは草むらへ帰っていった。',seedPlaceholder:'共有シード、または好きな言葉',debug:'テスト：集中30分を追加',reset:'リセット',statusTitle:'ポケモンの状態',recommendation:'推奨：640×280px以上の横長画像',install:'アプリをインストール',forestWaiting:'草むらが静かに待っています。',forestSub:'集中して得た探索券で出発しましょう。',timerDone:'タイマーが完了しました。',backupInvalid:'正しいPOKEDOROバックアップではありません。'
};
export function t(language: Language, key: Key): string { return ({ko,en,ja}[language][key] ?? ko[key]); }
export type TranslationKey = Key;
